version: "3.9"
services:
    postgre:
        container_name: gtfb_postgres
        image: postgres
        restart: always
        volumes:
            - ./data/pgdb:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: zayavka
            POSTGRES_USER: postgres
            POSTGRES_DB: zayavka
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8088:8080
    web:
        container_name: gtfb_webserver
        image: gtfb/host
        ports:
            - 8888:80
            - 443:443
            - 9110:9110
        volumes:
            - './sites:/var/www:delegated'
            - './config/nginx:/usr/local/openresty/nginx/sites:delegated'
            - './certbot-etc:/etc/letsencrypt:delegated'
            - './certbot-var:/var/lib/letsencrypt:delegated'
            - '.env:/usr/local/env/.env'
        tty: true
        restart: always
